version: '3.8'

services:
  # Development environment
  ecom-dashboard-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ecom-dashboard-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # Anonymous volume for node_modules
    environment:
      - NODE_ENV=development
    deploy:
      resources:
        limits:
          memory: 1500M
        reservations:
          memory: 512M
    networks:
      - ecom-network
    restart: unless-stopped

  # Production environment
  ecom-dashboard-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ecom-dashboard-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 1500M
        reservations:
          memory: 256M
    networks:
      - ecom-network
    restart: unless-stopped
    profiles:
      - production

networks:
  ecom-network:
    driver: bridge
    external: false